---
abstract: 'Interface to Google Zopfli Compression Algorithm'
author:
  - 'Marcel Greter <compress-zopfli@ocbnet.ch>'
build_requires:
  ExtUtils::CppGuess: 0.09
  ExtUtils::MakeMaker: 6.52
  Getopt::Long: 0.01
configure_requires:
  ExtUtils::CppGuess: 0.09
  ExtUtils::MakeMaker: 6.52
  Getopt::Long: 0.01
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120921'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Compress-Zopfli
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 1.01
  Getopt::Long: 0.01
  strict: 0
  version: 0
  warnings: 0
resources:
  bugtracker: https://github.com/mgreter/perl-zopfli/issues
  homepage: https://metacpan.org/release/Compress-Zopfli
  license: http://opensource.org/licenses/MIT
  repository: https://github.com/mgreter/perl-zopfli
version: v0.0.1
